export { ChokidarWatcher } from './backends/ChokidarWatcher';
export { FileWatchingBackend } from './backends/FileWatchingBackend';
export { FSWatcher } from './backends/FSWatcher';
export { TurboWatcher } from './backends/TurboWatcher';
export { createFileChangeQueue } from './createFileChangeQueue';
export { createSpawn } from './createSpawn';
export { deduplicateFileChangeEvents } from './deduplicateFileChangeEvents';
export { defineConfig } from './defineConfig';
export { AbortError, TurbowatchError, UnexpectedError } from './errors';
export { findNearestDirectory } from './findNearestDirectory';
export { generateShortId } from './generateShortId';
export { hashFile } from './hashFile';
export { isFSWatcherAvailable } from './isFSWatcherAvailable';
export { killPsTree } from './killPsTree';
export { Logger } from './Logger';
export { subscribe } from './subscribe';
export { testExpression } from './testExpression';
export { type ChangeEvent, type Expression, type TriggerInput } from './types';
export { watch } from './watch';
export { type ProcessPromise } from 'zx';
